/**
 * DATA RAYON SPMB DIY 2026/2027
 * Sumber: Juknis SPMB SMAN/SMKN DIY TA 2026-2027
 * Format: Optimized for GitHub Pages & Mobile
 * Usage: import { SMAN_RAYON } from './rayon_data.js';
 */

// Helper untuk normalisasi nama wilayah
const norm = (str) => str.replace(/Yo\s*gy\s*akarta/g, "Yogyakarta")
                         .replace(/Gunun\s*g\s*kidul/g, "Gunungkidul")
                         .replace(/Kulon\s*Pro\s*go/g, "Kulonprogo")
                         .replace(/\s+/g, " ").trim();

// Struktur: { desa, kecamatan, kabupaten, rayon1: [sekolah], rayon2: [sekolah] }
const SMAN_RAYON = [
{"d":"Mulyodadi","k":"Bambanglipuro","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Pundong"],"r2":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Sanden"]},
{"d":"Sidomulyo","k":"Bambanglipuro","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Pundong"],"r2":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Sanden"]},
{"d":"Sumbermulyo","k":"Bambanglipuro","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Bantul","SMAN 2 Bantul"],"r2":["SMAN 1 Kretek","SMAN 1 Pundong","SMAN 1 Sanden"]},
{"d":"Banguntapan","k":"Banguntapan","kb":"Bantul","r1":["SMAN 1 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 2 Banguntapan","SMAN 1 Depok","SMAN 9 Yogyakarta"]},
{"d":"Baturetno","k":"Banguntapan","kb":"Bantul","r1":["SMAN 1 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 2 Banguntapan","SMAN 1 Piyungan","SMAN 1 Depok"]},
{"d":"Jagalan","k":"Banguntapan","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 1 Banguntapan","SMAN 1 Piyungan","SMAN 7 Yogyakarta"]},
{"d":"Jambidan","k":"Banguntapan","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Pleret","SMAN 5 Yogyakarta"],"r2":["SMAN 1 Banguntapan","SMAN 1 Piyungan","SMAN 1 Sewon"]},
{"d":"Potorono","k":"Banguntapan","kb":"Bantul","r1":["SMAN 1 Banguntapan","SMAN 2 Banguntapan","SMAN 1 Piyungan"],"r2":["SMAN 1 Pleret","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Singosaren","k":"Banguntapan","kb":"Bantul","r1":["SMAN 1 Banguntapan","SMAN 2 Banguntapan","SMAN 5 Yogyakarta"],"r2":["SMAN 1 Piyungan","SMAN 1 Pleret","SMAN 8 Yogyakarta"]},
{"d":"Tamanan","k":"Banguntapan","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Pleret","SMAN 5 Yogyakarta"],"r2":["SMAN 1 Banguntapan","SMAN 1 Piyungan","SMAN 8 Yogyakarta"]},
{"d":"Wirokerten","k":"Banguntapan","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Pleret","SMAN 5 Yogyakarta"],"r2":["SMAN 1 Banguntapan","SMAN 1 Piyungan","SMAN 8 Yogyakarta"]},
{"d":"Bantul","k":"Bantul","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 3 Bantul"],"r2":["SMAN 1 Jetis","SMAN 1 Pajangan","SMAN 1 Sewon"]},
{"d":"Palbapang","k":"Bantul","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 3 Bantul"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Jetis","SMAN 1 Pajangan"]},
{"d":"Ringinharjo","k":"Bantul","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Pajangan"],"r2":["SMAN 1 Bambanglipuro","SMAN 3 Bantul","SMAN 1 Jetis"]},
{"d":"Sabdodadi","k":"Bantul","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 3 Bantul","SMAN 1 Jetis"],"r2":["SMAN 1 Bantul","SMAN 1 Imogiri","SMAN 1 Sewon"]},
{"d":"Trirenggo","k":"Bantul","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 3 Bantul"],"r2":["SMAN 1 Jetis","SMAN 1 Pajangan","SMAN 1 Sewon"]},
{"d":"Dlingo","k":"Dlingo","kb":"Bantul","r1":["SMAN 1 Dlingo","SMAN 1 Imogiri","SMAN 1 Playen"],"r2":["SMAN 1 Jetis","SMAN 1 Pundong","SMAN 1 Patuk"]},
{"d":"Jatimulyo","k":"Dlingo","kb":"Bantul","r1":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 1 Playen"],"r2":["SMAN 1 Imogiri","SMAN 1 Jetis","SMAN 1 Piyungan"]},
{"d":"Mangunan","k":"Dlingo","kb":"Bantul","r1":["SMAN 1 Dlingo","SMAN 1 Imogiri","SMAN 1 Jetis"],"r2":["SMAN 2 Banguntapan","SMAN 2 Bantul","SMAN 1 Piyungan"]},
{"d":"Muntuk","k":"Dlingo","kb":"Bantul","r1":["SMAN 1 Dlingo","SMAN 1 Imogiri","SMAN 1 Piyungan"],"r2":["SMAN 2 Banguntapan","SMAN 2 Bantul","SMAN 1 Pundong"]},
{"d":"Temuwuh","k":"Dlingo","kb":"Bantul","r1":["SMAN 1 Dlingo","SMAN 1 Imogiri","SMAN 1 Playen"],"r2":["SMAN 1 Piyungan","SMAN 1 Pleret","SMAN 1 Patuk"]},
{"d":"Terong","k":"Dlingo","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Dlingo","SMAN 1 Pleret"],"r2":["SMAN 1 Imogiri","SMAN 1 Jetis","SMAN 1 Piyungan"]},
{"d":"Girirejo","k":"Imogiri","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 1 Imogiri","SMAN 1 Jetis"],"r2":["SMAN 3 Bantul","SMAN 1 Pleret","SMAN 1 Pundong"]},
{"d":"Imogiri","k":"Imogiri","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 1 Imogiri","SMAN 1 Jetis"],"r2":["SMAN 1 Bantul","SMAN 3 Bantul","SMAN 1 Pleret"]},
{"d":"Karangtalun","k":"Imogiri","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 1 Imogiri","SMAN 1 Jetis"],"r2":["SMAN 1 Bantul","SMAN 3 Bantul","SMAN 1 Pleret"]},
{"d":"Karangtengah","k":"Imogiri","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 1 Imogiri","SMAN 1 Jetis"],"r2":["SMAN 1 Bantul","SMAN 3 Bantul","SMAN 1 Pleret"]},
{"d":"Kebonagung","k":"Imogiri","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 1 Imogiri","SMAN 1 Jetis"],"r2":["SMAN 1 Bantul","SMAN 1 Pleret","SMAN 1 Pundong"]},
{"d":"Selopamioro","k":"Imogiri","kb":"Bantul","r1":["SMAN 1 Imogiri","SMAN 1 Jetis","SMAN 1 Pundong"],"r2":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Pleret"]},
{"d":"Sriharjo","k":"Imogiri","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 1 Imogiri","SMAN 1 Jetis"],"r2":["SMAN 1 Bantul","SMAN 1 Pleret","SMAN 1 Pundong"]},
{"d":"Wukirsari","k":"Imogiri","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 1 Imogiri","SMAN 1 Jetis"],"r2":["SMAN 1 Bantul","SMAN 1 Pleret","SMAN 1 Pundong"]},
{"d":"Canden","k":"Jetis","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 1 Jetis","SMAN 1 Pundong"],"r2":["SMAN 1 Bantul","SMAN 1 Imogiri","SMAN 1 Pleret"]},
{"d":"Patalan","k":"Jetis","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 3 Bantul","SMAN 1 Pundong"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Bantul","SMAN 1 Jetis"]},
{"d":"Sumberagung","k":"Jetis","kb":"Bantul","r1":["SMAN 2 Bantul","SMAN 3 Bantul","SMAN 1 Jetis"],"r2":["SMAN 1 Bantul","SMAN 1 Imogiri","SMAN 1 Pundong"]},
{"d":"Trimulyo","k":"Jetis","kb":"Bantul","r1":["SMAN 1 Imogiri","SMAN 1 Jetis","SMAN 1 Pleret"],"r2":["SMAN 2 Bantul","SMAN 3 Bantul","SMAN 1 Pundong"]},
{"d":"Bangunjiwo","k":"Kasihan","kb":"Bantul","r1":["SMAN 1 Kasihan","SMAN 1 Pajangan","SMAN 1 Sewon"],"r2":["SMAN 2 Bantul","SMAN 3 Bantul","SMAN 7 Yogyakarta"]},
{"d":"Ngestiharjo","k":"Kasihan","kb":"Bantul","r1":["SMAN 1 Kasihan","SMAN 10 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Gamping","SMAN 7 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Tamantirto","k":"Kasihan","kb":"Bantul","r1":["SMAN 1 Kasihan","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Sewon","SMAN 1 Gamping","SMAN 10 Yogyakarta"]},
{"d":"Tirtonirmolo","k":"Kasihan","kb":"Bantul","r1":["SMAN 1 Kasihan","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Sewon","SMAN 1 Gamping","SMAN 10 Yogyakarta"]},
{"d":"Donotirto","k":"Kretek","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Pundong"],"r2":["SMAN 1 Bantul","SMAN 1 Sanden","SMAN 1 Srandakan"]},
{"d":"Parangtritis","k":"Kretek","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Pundong"],"r2":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Sanden"]},
{"d":"Tirtohargo","k":"Kretek","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Sanden"],"r2":["SMAN 1 Bantul","SMAN 1 Pundong","SMAN 1 Srandakan"]},
{"d":"Tirtomulyo","k":"Kretek","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Sanden"],"r2":["SMAN 1 Bantul","SMAN 1 Pundong","SMAN 1 Srandakan"]},
{"d":"Tirtosari","k":"Kretek","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Sanden"],"r2":["SMAN 1 Bantul","SMAN 1 Pundong","SMAN 1 Srandakan"]},
{"d":"Guwosari","k":"Pajangan","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 3 Bantul","SMAN 1 Pajangan"],"r2":["SMAN 1 Bambanglipuro","SMAN 2 Bantul","SMAN 1 Srandakan"]},
{"d":"Sendangsari","k":"Pajangan","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Pajangan"],"r2":["SMAN 1 Bambanglipuro","SMAN 3 Bantul","SMAN 1 Srandakan"]},
{"d":"Triwidadi","k":"Pajangan","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 1 Pajangan","SMAN 1 Sedayu"],"r2":["SMAN 2 Bantul","SMAN 3 Bantul","SMAN 1 Sentolo"]},
{"d":"Caturharjo","k":"Pandak","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Sanden","SMAN 1 Srandakan"],"r2":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Pajangan"]},
{"d":"Gilangharjo","k":"Pandak","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Bantul","SMAN 2 Bantul"],"r2":["SMAN 1 Kretek","SMAN 1 Pajangan","SMAN 1 Pundong"]},
{"d":"Triharjo","k":"Pandak","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Pajangan","SMAN 1 Sanden"],"r2":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Srandakan"]},
{"d":"Wijirejo","k":"Pandak","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 2 Bantul","SMAN 1 Pajangan"],"r2":["SMAN 1 Bambanglipuro","SMAN 3 Bantul","SMAN 1 Srandakan"]},
{"d":"Sitimulyo","k":"Piyungan","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Piyungan","SMAN 1 Pleret"],"r2":["SMAN 1 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Srimartani","k":"Piyungan","kb":"Bantul","r1":["SMAN 1 Piyungan","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 2 Banguntapan","SMAN 1 Pleret"]},
{"d":"Srimulyo","k":"Piyungan","kb":"Bantul","r1":["SMAN 1 Banguntapan","SMAN 1 Piyungan","SMAN 5 Yogyakarta"],"r2":["SMAN 2 Banguntapan","SMAN 1 Pleret","SMAN 8 Yogyakarta"]},
{"d":"Bawuran","k":"Pleret","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Piyungan","SMAN 1 Pleret"],"r2":["SMAN 1 Banguntapan","SMAN 1 Jetis","SMAN 1 Sewon"]},
{"d":"Pleret","k":"Pleret","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Jetis","SMAN 1 Pleret"],"r2":["SMAN 1 Banguntapan","SMAN 1 Imogiri","SMAN 1 Sewon"]},
{"d":"Segoroyoso","k":"Pleret","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Imogiri","SMAN 1 Pleret"],"r2":["SMAN 1 Banguntapan","SMAN 1 Jetis","SMAN 1 Sewon"]},
{"d":"Wonokromo","k":"Pleret","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Jetis","SMAN 1 Pleret"],"r2":["SMAN 3 Bantul","SMAN 1 Imogiri","SMAN 1 Sewon"]},
{"d":"Wonolelo","k":"Pleret","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Piyungan","SMAN 1 Pleret"],"r2":["SMAN 1 Imogiri","SMAN 1 Jetis","SMAN 1 Sewon"]},
{"d":"Panjangrejo","k":"Pundong","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Pundong"],"r2":["SMAN 1 Bantul","SMAN 1 Pajangan","SMAN 1 Sanden"]},
{"d":"Seloharjo","k":"Pundong","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Pundong"],"r2":["SMAN 1 Bantul","SMAN 1 Imogiri","SMAN 1 Sanden"]},
{"d":"Srihardono","k":"Pundong","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Pundong"],"r2":["SMAN 1 Imogiri","SMAN 1 Jetis","SMAN 1 Bantul"]},
{"d":"Gadingharjo","k":"Sanden","kb":"Bantul","r1":["SMAN 1 Kretek","SMAN 1 Sanden","SMAN 1 Srandakan"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Pundong","SMAN 1 Lendah"]},
{"d":"Gadingsari","k":"Sanden","kb":"Bantul","r1":["SMAN 1 Kretek","SMAN 1 Sanden","SMAN 1 Srandakan"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Pundong","SMAN 1 Lendah"]},
{"d":"Murtigading","k":"Sanden","kb":"Bantul","r1":["SMAN 1 Kretek","SMAN 1 Sanden","SMAN 1 Srandakan"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Pundong","SMAN 1 Lendah"]},
{"d":"Srigading","k":"Sanden","kb":"Bantul","r1":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Sanden"],"r2":["SMAN 1 Pundong","SMAN 1 Srandakan","SMAN 1 Lendah"]},
{"d":"Argodadi","k":"Sedayu","kb":"Bantul","r1":["SMAN 1 Pajangan","SMAN 1 Sedayu","SMAN 1 Sentolo"],"r2":["SMAN 1 Bantul","SMAN 1 Girimulyo","SMAN 1 Lendah"]},
{"d":"Argomulyo","k":"Sedayu","kb":"Bantul","r1":["SMAN 1 Sedayu","SMAN 1 Sentolo","SMAN 1 Godean"],"r2":["SMAN 1 Girimulyo","SMAN 1 Gamping","SMAN 1 Minggir"]},
{"d":"Argorejo","k":"Sedayu","kb":"Bantul","r1":["SMAN 1 Sedayu","SMAN 1 Sentolo","SMAN 1 Minggir"],"r2":["SMAN 1 Pajangan","SMAN 1 Girimulyo","SMAN 1 Gamping"]},
{"d":"Argosari","k":"Sedayu","kb":"Bantul","r1":["SMAN 1 Sedayu","SMAN 1 Sentolo","SMAN 1 Minggir"],"r2":["SMAN 1 Pajangan","SMAN 1 Girimulyo","SMAN 1 Godean"]},
{"d":"Bangunharjo","k":"Sewon","kb":"Bantul","r1":["SMAN 2 Banguntapan","SMAN 1 Jetis","SMAN 1 Sewon"],"r2":["SMAN 1 Kasihan","SMAN 5 Yogyakarta","SMAN 7 Yogyakarta"]},
{"d":"Panggungharjo","k":"Sewon","kb":"Bantul","r1":["SMAN 1 Kasihan","SMAN 1 Sewon","SMAN 7 Yogyakarta"],"r2":["SMAN 2 Banguntapan","SMAN 1 Jetis","SMAN 5 Yogyakarta"]},
{"d":"Pendowoharjo","k":"Sewon","kb":"Bantul","r1":["SMAN 1 Bantul","SMAN 3 Bantul","SMAN 1 Sewon"],"r2":["SMAN 1 Jetis","SMAN 1 Kasihan","SMAN 7 Yogyakarta"]},
{"d":"Timbulharjo","k":"Sewon","kb":"Bantul","r1":["SMAN 3 Bantul","SMAN 1 Jetis","SMAN 1 Sewon"],"r2":["SMAN 1 Bantul","SMAN 1 Imogiri","SMAN 7 Yogyakarta"]},
{"d":"Poncosari","k":"Srandakan","kb":"Bantul","r1":["SMAN 1 Sanden","SMAN 1 Srandakan","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Galur"]},
{"d":"Trimurti","k":"Srandakan","kb":"Bantul","r1":["SMAN 1 Sanden","SMAN 1 Srandakan","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Bantul","SMAN 1 Kretek"]},
{"d":"Hargomulyo","k":"Gedangsari","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Semin","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Mertelu","k":"Gedangsari","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Semanu","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Ngalang","k":"Gedangsari","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Sampang","k":"Gedangsari","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Piyungan","SMAN 2 Playen","SMAN 1 Wonosari"]},
{"d":"Serut","k":"Gedangsari","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 1 Piyungan","SMAN 5 Yogyakarta"]},
{"d":"Tegalrejo","k":"Gedangsari","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Semin","SMAN 1 Kalasan"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 1 Prambanan"]},
{"d":"Watugajah","k":"Gedangsari","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Piyungan","SMAN 2 Playen","SMAN 1 Wonosari"]},
{"d":"Balong","k":"Girisubo","kb":"Gunungkidul","r1":["SMAN 1 Rongkop","SMAN 1 Semanu","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Jepitu","k":"Girisubo","kb":"Gunungkidul","r1":["SMAN 1 Rongkop","SMAN 1 Semanu","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Jerukwudel","k":"Girisubo","kb":"Gunungkidul","r1":["SMAN 1 Rongkop","SMAN 1 Semanu","SMAN 1 Tanjungsari"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Karangawen","k":"Girisubo","kb":"Gunungkidul","r1":["SMAN 1 Rongkop","SMAN 1 Semanu","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Nglindur","k":"Girisubo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Pucung","k":"Girisubo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Songbanyu","k":"Girisubo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Tileng","k":"Girisubo","kb":"Gunungkidul","r1":["SMAN 1 Rongkop","SMAN 1 Semanu","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Bejiharjo","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"]},
{"d":"Bendungan","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"]},
{"d":"Gedangrejo","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semin","SMAN 2 Wonosari"]},
{"d":"Jatiayu","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Karangmojo","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semin","SMAN 2 Wonosari"]},
{"d":"Kelor","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semanu","SMAN 1 Tanjungsari"]},
{"d":"Ngawis","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semanu","SMAN 1 Semin"]},
{"d":"Ngipak","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semin","SMAN 2 Wonosari"]},
{"d":"Wiladeg","k":"Karangmojo","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Semanu"]},
{"d":"Beji","k":"Ngawen","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Jurangjero","k":"Ngawen","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Kampung","k":"Ngawen","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Sambirejo","k":"Ngawen","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 1 Patuk","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Tancep","k":"Ngawen","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Watusigar","k":"Ngawen","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Katongan","k":"Nglipar","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Semin","SMAN 2 Wonosari"]},
{"d":"Kedungkeris","k":"Nglipar","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 1 Playen"]},
{"d":"Kedungpoh","k":"Nglipar","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Semin","SMAN 2 Wonosari"]},
{"d":"Natah","k":"Nglipar","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Nglipar","k":"Nglipar","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 1 Playen"]},
{"d":"Pengkol","k":"Nglipar","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Playen","SMAN 1 Semin","SMAN 2 Wonosari"]},
{"d":"Pilangrejo","k":"Nglipar","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Semin","SMAN 1 Wonosari"],"r2":["SMAN 1 Playen","SMAN 2 Playen","SMAN 2 Wonosari"]},
{"d":"Giring","k":"Paliyan","kb":"Gunungkidul","r1":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Semanu"]},
{"d":"Grogol","k":"Paliyan","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semanu","SMAN 1 Tanjungsari"]},
{"d":"Karangasem","k":"Paliyan","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semanu","SMAN 1 Tanjungsari"]},
{"d":"Karangduwet","k":"Paliyan","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Panggang","SMAN 2 Playen","SMAN 1 Tanjungsari"]},
{"d":"Mulusan","k":"Paliyan","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semanu","SMAN 1 Tanjungsari"]},
{"d":"Pampang","k":"Paliyan","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semanu","SMAN 1 Tanjungsari"]},
{"d":"Sodo","k":"Paliyan","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Semanu","SMAN 1 Tanjungsari"]},
{"d":"Giriharjo","k":"Panggang","kb":"Gunungkidul","r1":["SMAN 1 Imogiri","SMAN 1 Jetis","SMAN 1 Panggang"],"r2":["SMAN 2 Bantul","SMAN 1 Pundong","SMAN 1 Playen"]},
{"d":"Girikarto","k":"Panggang","kb":"Gunungkidul","r1":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Jetis","SMAN 1 Kretek","SMAN 1 Wonosari"]},
{"d":"Girimulyo","k":"Panggang","kb":"Gunungkidul","r1":["SMAN 1 Imogiri","SMAN 1 Panggang","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Pundong","SMAN 1 Playen","SMAN 2 Wonosari"]},
{"d":"Girisekar","k":"Panggang","kb":"Gunungkidul","r1":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 1 Tanjungsari"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Girisuko","k":"Panggang","kb":"Gunungkidul","r1":["SMAN 1 Imogiri","SMAN 1 Jetis","SMAN 1 Panggang"],"r2":["SMAN 1 Kretek","SMAN 1 Pundong","SMAN 1 Playen"]},
{"d":"Giriwungu","k":"Panggang","kb":"Gunungkidul","r1":["SMAN 1 Jetis","SMAN 1 Pundong","SMAN 1 Panggang"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Dlingo","SMAN 1 Kretek"]},
{"d":"Beji","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 2 Playen"],"r2":["SMAN 1 Piyungan","SMAN 1 Playen","SMAN 1 Wonosari"]},
{"d":"Bunder","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Nglanggeran","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Dlingo","SMAN 1 Piyungan","SMAN 1 Prambanan"]},
{"d":"Nglegi","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Ngoro-oro","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Piyungan","SMAN 1 Patuk","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 2 Playen","SMAN 5 Yogyakarta"]},
{"d":"Patuk","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Piyungan","SMAN 1 Patuk","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 1 Dlingo","SMAN 5 Yogyakarta"]},
{"d":"Pengkok","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Dlingo","SMAN 1 Piyungan","SMAN 1 Patuk"],"r2":["SMAN 1 Banguntapan","SMAN 2 Playen","SMAN 1 Prambanan"]},
{"d":"Putat","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 2 Playen"],"r2":["SMAN 1 Piyungan","SMAN 1 Playen","SMAN 1 Prambanan"]},
{"d":"Salam","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Piyungan","SMAN 1 Patuk","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 2 Playen","SMAN 5 Yogyakarta"]},
{"d":"Semoyo","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Dlingo","SMAN 1 Piyungan","SMAN 1 Patuk"],"r2":["SMAN 1 Banguntapan","SMAN 2 Playen","SMAN 1 Prambanan"]},
{"d":"Terbah","k":"Patuk","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Piyungan","SMAN 2 Playen","SMAN 1 Semin"]},
{"d":"Banaran","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Bandung","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 2 Wonosari"]},
{"d":"Banyusoco","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Bleberan","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 2 Wonosari"]},
{"d":"Dengok","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 2 Wonosari"]},
{"d":"Gading","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Getas","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Dlingo","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Patuk","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Logandeng","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 2 Wonosari"]},
{"d":"Ngawu","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 2 Wonosari"]},
{"d":"Ngleri","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Patuk","SMAN 1 Playen","SMAN 2 Playen"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Ngunut","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 2 Wonosari"]},
{"d":"Playen","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Wonosari"],"r2":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 2 Wonosari"]},
{"d":"Plembutan","k":"Playen","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 2 Playen","SMAN 2 Wonosari"],"r2":["SMAN 1 Dlingo","SMAN 1 Patuk","SMAN 1 Wonosari"]},
{"d":"Bedoyo","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Genjahan","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Gombang","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 2 Wonosari"],"r2":["SMAN 1 Rongkop","SMAN 1 Tanjungsari","SMAN 1 Wonosari"]},
{"d":"Karangasem","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Kenteng","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Semin","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Ponjong","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Sawahan","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 1 Rongkop","SMAN 1 Tanjungsari","SMAN 1 Wonosari"]},
{"d":"Sidorejo","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Rongkop","SMAN 1 Wonosari"]},
{"d":"Sumbergiri","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Semin","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Tambakromo","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 1 Rongkop","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Umbulrejo","k":"Ponjong","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Wonosari"],"r2":["SMAN 1 Rongkop","SMAN 1 Semin","SMAN 2 Wonosari"]},
{"d":"Giriasih","k":"Purwosari","kb":"Gunungkidul","r1":["SMAN 1 Kretek","SMAN 1 Pundong","SMAN 1 Panggang"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Dlingo","SMAN 1 Imogiri"]},
{"d":"Giricahyo","k":"Purwosari","kb":"Gunungkidul","r1":["SMAN 1 Kretek","SMAN 1 Pundong","SMAN 1 Panggang"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Dlingo","SMAN 1 Imogiri"]},
{"d":"Girijati","k":"Purwosari","kb":"Gunungkidul","r1":["SMAN 1 Kretek","SMAN 1 Pundong","SMAN 1 Panggang"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Imogiri","SMAN 1 Sanden"]},
{"d":"Giripurwo","k":"Purwosari","kb":"Gunungkidul","r1":["SMAN 1 Kretek","SMAN 1 Pundong","SMAN 1 Panggang"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Dlingo","SMAN 1 Jetis"]},
{"d":"Giritirto","k":"Purwosari","kb":"Gunungkidul","r1":["SMAN 1 Kretek","SMAN 1 Pundong","SMAN 1 Panggang"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Dlingo","SMAN 1 Imogiri"]},
{"d":"Bohol","k":"Rongkop","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Botodayakan","k":"Rongkop","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Karangwuni","k":"Rongkop","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Semin","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Melikan","k":"Rongkop","kb":"Gunungkidul","r1":["SMAN 1 Rongkop","SMAN 1 Semanu","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Tanjungsari","SMAN 1 Wonosari"]},
{"d":"Petir","k":"Rongkop","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Pringombo","k":"Rongkop","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Pucanganom","k":"Rongkop","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Semugih","k":"Rongkop","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Jetis","k":"Saptosari","kb":"Gunungkidul","r1":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Kanigoro","k":"Saptosari","kb":"Gunungkidul","r1":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Semanu","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Kepek","k":"Saptosari","kb":"Gunungkidul","r1":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Krambilsawit","k":"Saptosari","kb":"Gunungkidul","r1":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Monggol","k":"Saptosari","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 1 Tanjungsari","SMAN 2 Wonosari"],"r2":["SMAN 1 Panggang","SMAN 1 Semanu","SMAN 1 Wonosari"]},
{"d":"Nglora","k":"Saptosari","kb":"Gunungkidul","r1":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Dlingo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Planjan","k":"Saptosari","kb":"Gunungkidul","r1":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Panggang","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Candirejo","k":"Semanu","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Rongkop","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Dadapayu","k":"Semanu","kb":"Gunungkidul","r1":["SMAN 1 Rongkop","SMAN 1 Semanu","SMAN 2 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Tanjungsari","SMAN 1 Wonosari"]},
{"d":"Ngeposari","k":"Semanu","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 1 Rongkop","SMAN 1 Wonosari"]},
{"d":"Pacarejo","k":"Semanu","kb":"Gunungkidul","r1":["SMAN 1 Semanu","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 2 Playen"]},
{"d":"Semanu","k":"Semanu","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Wonosari"],"r2":["SMAN 2 Playen","SMAN 1 Tanjungsari","SMAN 2 Wonosari"]},
{"d":"Bendung","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Bulurejo","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Candirejo","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Kalitekuk","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 1 Patuk","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Karangsari","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Kemejing","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Pundungsari","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Rejosari","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 1 Rongkop","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Semin","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Sumberrejo","k":"Semin","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Semin"],"r2":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Banjarejo","k":"Tanjungsari","kb":"Gunungkidul","r1":["SMAN 1 Semanu","SMAN 1 Tanjungsari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Wonosari"]},
{"d":"Hargosari","k":"Tanjungsari","kb":"Gunungkidul","r1":["SMAN 1 Semanu","SMAN 1 Tanjungsari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Wonosari"]},
{"d":"Kemadang","k":"Tanjungsari","kb":"Gunungkidul","r1":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Kemiri","k":"Tanjungsari","kb":"Gunungkidul","r1":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Semanu"]},
{"d":"Ngestirejo","k":"Tanjungsari","kb":"Gunungkidul","r1":["SMAN 1 Semanu","SMAN 1 Tanjungsari","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 1 Rongkop","SMAN 1 Wonosari"]},
{"d":"Giripanggung","k":"Tepus","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Semanu"],"r2":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Purwodadi","k":"Tepus","kb":"Gunungkidul","r1":["SMAN 1 Rongkop","SMAN 1 Semanu","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Sidoharjo","k":"Tepus","kb":"Gunungkidul","r1":["SMAN 1 Semanu","SMAN 1 Tanjungsari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Wonosari"]},
{"d":"Sumberwungu","k":"Tepus","kb":"Gunungkidul","r1":["SMAN 1 Karangmojo","SMAN 1 Semanu","SMAN 1 Tanjungsari"],"r2":["SMAN 1 Rongkop","SMAN 1 Wonosari","SMAN 2 Wonosari"]},
{"d":"Tepus","k":"Tepus","kb":"Gunungkidul","r1":["SMAN 1 Semanu","SMAN 1 Tanjungsari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Rongkop","SMAN 1 Wonosari"]},
{"d":"Baleharjo","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Duwet","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 1 Semanu","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Tanjungsari"]},
{"d":"Gari","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 1 Playen"]},
{"d":"Karangrejek","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Karangtengah","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Patuk","SMAN 1 Playen"]},
{"d":"Kepek","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Mulo","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Semanu"]},
{"d":"Piyaman","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Pulutan","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 1 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 2 Playen","SMAN 1 Semanu"]},
{"d":"Selang","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Siraman","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Wareng","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 1 Semanu","SMAN 1 Tanjungsari"]},
{"d":"Wonosari","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 2 Playen","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Karangmojo","SMAN 1 Playen","SMAN 1 Semanu"]},
{"d":"Wunung","k":"Wonosari","kb":"Gunungkidul","r1":["SMAN 1 Tanjungsari","SMAN 1 Wonosari","SMAN 2 Wonosari"],"r2":["SMAN 1 Playen","SMAN 2 Playen","SMAN 1 Semanu"]},
{"d":"Banaran","k":"Galur","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Sanden","SMAN 2 Wates"]},
{"d":"Brosot","k":"Galur","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Sanden"]},
{"d":"Karangsewu","k":"Galur","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Sanden","SMAN 2 Wates"]},
{"d":"Kranggan","k":"Galur","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Sanden","SMAN 2 Wates"]},
{"d":"Nomporejo","k":"Galur","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Kretek","SMAN 1 Sanden","SMAN 2 Wates"]},
{"d":"Pandowan","k":"Galur","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Sanden","SMAN 2 Wates"]},
{"d":"Tirtarahayu","k":"Galur","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Sanden","SMAN 2 Wates"]},
{"d":"Giripurwo","k":"Girimulyo","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Sentolo","SMAN 1 Minggir"],"r2":["SMAN 1 Kalibawang","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Jatimulyo","k":"Girimulyo","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Sentolo","SMAN 1 Minggir"],"r2":["SMAN 1 Kalibawang","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Pendoworejo","k":"Girimulyo","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Sedayu","SMAN 1 Sentolo","SMAN 1 Godean"]},
{"d":"Purwosari","k":"Girimulyo","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Samigaluh","SMAN 1 Minggir"],"r2":["SMAN 1 Kalibawang","SMAN 1 Pengasih","SMAN 1 Sentolo"]},
{"d":"Banjararum","k":"Kalibawang","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Samigaluh","SMAN 1 Sentolo","SMAN 1 Godean"]},
{"d":"Banjarasri","k":"Kalibawang","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Samigaluh","SMAN 1 Godean","SMAN 1 Seyegan"]},
{"d":"Banjarharjo","k":"Kalibawang","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Samigaluh","SMAN 1 Godean","SMAN 1 Seyegan"]},
{"d":"Banjaroyo","k":"Kalibawang","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Seyegan","SMAN 1 Sleman","SMAN 1 Tempel"]},
{"d":"Hargomulyo","k":"Kokap","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Hargorejo","k":"Kokap","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Temon"]},
{"d":"Hargotirto","k":"Kokap","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Pengasih","SMAN 1 Wates"],"r2":["SMAN 1 Girimulyo","SMAN 1 Temon","SMAN 2 Wates"]},
{"d":"Hargowilis","k":"Kokap","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Pengasih","SMAN 1 Wates"],"r2":["SMAN 1 Girimulyo","SMAN 1 Temon","SMAN 2 Wates"]},
{"d":"Kalirejo","k":"Kokap","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Girimulyo","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Bumirejo","k":"Lendah","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Lendah","SMAN 1 Pengasih"],"r2":["SMAN 1 Srandakan","SMAN 1 Wates","SMAN 2 Wates"]},
{"d":"Gulurejo","k":"Lendah","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Pajangan","SMAN 1 Sanden"]},
{"d":"Jatirejo","k":"Lendah","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Sanden"]},
{"d":"Ngentakrejo","k":"Lendah","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Sanden"]},
{"d":"Sidorejo","k":"Lendah","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Bambanglipuro","SMAN 1 Kretek","SMAN 1 Sanden"]},
{"d":"Wahyuharjo","k":"Lendah","kb":"Kulonprogo","r1":["SMAN 1 Srandakan","SMAN 1 Galur","SMAN 1 Lendah"],"r2":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"]},
{"d":"Banyuroto","k":"Nanggulan","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Sentolo","SMAN 1 Wates"],"r2":["SMAN 1 Sedayu","SMAN 1 Girimulyo","SMAN 2 Wates"]},
{"d":"Donomulyo","k":"Nanggulan","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Sentolo","SMAN 1 Wates"],"r2":["SMAN 1 Sedayu","SMAN 1 Girimulyo","SMAN 1 Minggir"]},
{"d":"Jatisarono","k":"Nanggulan","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Sedayu","SMAN 1 Sentolo","SMAN 1 Godean"]},
{"d":"Kembang","k":"Nanggulan","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Pengasih","SMAN 1 Sentolo","SMAN 1 Godean"]},
{"d":"Tanjungharjo","k":"Nanggulan","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Sentolo","SMAN 1 Minggir"],"r2":["SMAN 1 Kalibawang","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Wijimulyo","k":"Nanggulan","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Sentolo","SMAN 1 Minggir"],"r2":["SMAN 1 Sedayu","SMAN 1 Kalibawang","SMAN 1 Pengasih"]},
{"d":"Bojong","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Lendah","SMAN 1 Pengasih","SMAN 1 Temon"]},
{"d":"Bugel","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Lendah","SMAN 1 Pengasih","SMAN 1 Temon"]},
{"d":"Cerme","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 2 Wates"],"r2":["SMAN 1 Srandakan","SMAN 1 Lendah","SMAN 1 Wates"]},
{"d":"Depok","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Srandakan","SMAN 1 Lendah","SMAN 1 Pengasih"]},
{"d":"Garongan","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Lendah","SMAN 1 Pengasih","SMAN 1 Temon"]},
{"d":"Gotakan","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 2 Wates"],"r2":["SMAN 1 Lendah","SMAN 1 Temon","SMAN 1 Wates"]},
{"d":"Kanoman","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 2 Wates"],"r2":["SMAN 1 Srandakan","SMAN 1 Lendah","SMAN 1 Wates"]},
{"d":"Krembangan","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 2 Wates"],"r2":["SMAN 1 Srandakan","SMAN 1 Lendah","SMAN 1 Wates"]},
{"d":"Panjatan","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 2 Wates"],"r2":["SMAN 1 Srandakan","SMAN 1 Lendah","SMAN 1 Wates"]},
{"d":"Pleret","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Srandakan","SMAN 1 Lendah","SMAN 1 Pengasih"]},
{"d":"Tayuban","k":"Panjatan","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Lendah","SMAN 1 Pengasih","SMAN 1 Temon"]},
{"d":"Karangsari","k":"Pengasih","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Temon"]},
{"d":"Kedungsari","k":"Pengasih","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Lendah","SMAN 1 Sentolo"]},
{"d":"Margosari","k":"Pengasih","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Kokap","SMAN 1 Lendah","SMAN 1 Sentolo"]},
{"d":"Pengasih","k":"Pengasih","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Sentolo"]},
{"d":"Sendangsari","k":"Pengasih","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Sentolo"]},
{"d":"Sidomulyo","k":"Pengasih","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Sentolo"]},
{"d":"Tawangsari","k":"Pengasih","kb":"Kulonprogo","r1":["SMAN 1 Temon","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Pengasih"]},
{"d":"Banjarsari","k":"Samigaluh","kb":"Kulonprogo","r1":["SMAN 1 Kalibawang","SMAN 1 Samigaluh","SMAN 1 Girimulyo"],"r2":["SMAN 1 Sentolo","SMAN 1 Godean","SMAN 1 Mlati"]},
{"d":"Gerbosari","k":"Samigaluh","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Samigaluh"],"r2":["SMAN 1 Sedayu","SMAN 1 Godean","SMAN 1 Minggir"]},
{"d":"Kebonharjo","k":"Samigaluh","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Samigaluh"],"r2":["SMAN 1 Sedayu","SMAN 1 Sentolo","SMAN 1 Godean"]},
{"d":"Ngargosari","k":"Samigaluh","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Samigaluh"],"r2":["SMAN 1 Sentolo","SMAN 1 Minggir","SMAN 1 Seyegan"]},
{"d":"Pagerharjo","k":"Samigaluh","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Samigaluh"],"r2":["SMAN 1 Sentolo","SMAN 1 Minggir","SMAN 1 Seyegan"]},
{"d":"Purwoharjo","k":"Samigaluh","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Samigaluh"],"r2":["SMAN 1 Sentolo","SMAN 1 Minggir","SMAN 1 Seyegan"]},
{"d":"Sidoharjo","k":"Samigaluh","kb":"Kulonprogo","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Samigaluh"],"r2":["SMAN 1 Sentolo","SMAN 1 Minggir","SMAN 1 Seyegan"]},
{"d":"Banguncipto","k":"Sentolo","kb":"Kulonprogo","r1":["SMAN 1 Sedayu","SMAN 1 Girimulyo","SMAN 1 Sentolo"],"r2":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 1 Minggir"]},
{"d":"Demangrejo","k":"Sentolo","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Lendah","SMAN 1 Pengasih"],"r2":["SMAN 1 Srandakan","SMAN 1 Wates","SMAN 2 Wates"]},
{"d":"Kaliagung","k":"Sentolo","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Sentolo","SMAN 1 Wates"],"r2":["SMAN 1 Sedayu","SMAN 1 Girimulyo","SMAN 1 Minggir"]},
{"d":"Salamrejo","k":"Sentolo","kb":"Kulonprogo","r1":["SMAN 1 Sedayu","SMAN 1 Pengasih","SMAN 1 Sentolo"],"r2":["SMAN 1 Girimulyo","SMAN 1 Wates","SMAN 2 Wates"]},
{"d":"Sentolo","k":"Sentolo","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Sentolo","SMAN 1 Wates"],"r2":["SMAN 1 Sedayu","SMAN 1 Girimulyo","SMAN 2 Wates"]},
{"d":"Srikayangan","k":"Sentolo","kb":"Kulonprogo","r1":["SMAN 1 Galur","SMAN 1 Lendah","SMAN 1 Pengasih"],"r2":["SMAN 1 Srandakan","SMAN 1 Wates","SMAN 2 Wates"]},
{"d":"Sukoreno","k":"Sentolo","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Sentolo","SMAN 1 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Lendah","SMAN 2 Wates"]},
{"d":"Tuksono","k":"Sentolo","kb":"Kulonprogo","r1":["SMAN 1 Lendah","SMAN 1 Pengasih","SMAN 1 Sentolo"],"r2":["SMAN 1 Pajangan","SMAN 1 Srandakan","SMAN 1 Galur"]},
{"d":"Demen","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Glagah","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Jangkaran","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Janten","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Kalidengen","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Kaligintung","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Karangwuluh","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Kebonrejo","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Kedundang","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Temon","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Pengasih"]},
{"d":"Kulur","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Temon","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Pengasih"]},
{"d":"Palihan","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Plumbon","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Temon","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Pengasih"]},
{"d":"Sindutan","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Temon Kulon","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Temon Wetan","k":"Temon","kb":"Kulonprogo","r1":["SMAN 1 Kokap","SMAN 1 Temon","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Pengasih","SMAN 1 Wates"]},
{"d":"Bendungan","k":"Wates","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Temon"]},
{"d":"Giripeni","k":"Wates","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Temon"]},
{"d":"Karangwuni","k":"Wates","kb":"Kulonprogo","r1":["SMAN 1 Temon","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Pengasih"]},
{"d":"Kulwaru","k":"Wates","kb":"Kulonprogo","r1":["SMAN 1 Temon","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Pengasih"]},
{"d":"Ngestiharjo","k":"Wates","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Temon"]},
{"d":"Sogan","k":"Wates","kb":"Kulonprogo","r1":["SMAN 1 Temon","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Pengasih"]},
{"d":"Triharjo","k":"Wates","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Galur","SMAN 1 Kokap","SMAN 1 Temon"]},
{"d":"Wates","k":"Wates","kb":"Kulonprogo","r1":["SMAN 1 Pengasih","SMAN 1 Wates","SMAN 2 Wates"],"r2":["SMAN 1 Sedayu","SMAN 1 Kokap","SMAN 1 Temon"]},
{"d":"Jogotirto","k":"Berbah","kb":"Sleman","r1":["SMAN 1 Banguntapan","SMAN 1 Piyungan","SMAN 1 Prambanan"],"r2":["SMAN 1 Kalasan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Kalitirto","k":"Berbah","kb":"Sleman","r1":["SMAN 1 Banguntapan","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Piyungan","SMAN 1 Depok","SMAN 8 Yogyakarta"]},
{"d":"Sendangtirto","k":"Berbah","kb":"Sleman","r1":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 8 Yogyakarta"],"r2":["SMAN 2 Banguntapan","SMAN 1 Depok","SMAN 8 Yogyakarta"]},
{"d":"Tegaltirto","k":"Berbah","kb":"Sleman","r1":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 8 Yogyakarta"],"r2":["SMAN 1 Depok","SMAN 1 Prambanan","SMAN 5 Yogyakarta"]},
{"d":"Argomulyo","k":"Cangkringan","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 2 Ngaglik","SMAN 1 Ngemplak"],"r2":["SMAN 1 Ngaglik","SMAN 1 Pakem","SMAN 1 Prambanan"]},
{"d":"Glagahharjo","k":"Cangkringan","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 1 Ngemplak","SMAN 1 Pakem"],"r2":["SMAN 1 Ngaglik","SMAN 2 Ngaglik","SMAN 1 Turi"]},
{"d":"Kepuharjo","k":"Cangkringan","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 1 Ngemplak","SMAN 1 Pakem"],"r2":["SMAN 1 Ngaglik","SMAN 2 Ngaglik","SMAN 1 Turi"]},
{"d":"Umbulharjo","k":"Cangkringan","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 2 Ngaglik","SMAN 1 Pakem"],"r2":["SMAN 1 Ngaglik","SMAN 1 Ngemplak","SMAN 1 Turi"]},
{"d":"Wukirsari","k":"Cangkringan","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 1 Ngemplak","SMAN 1 Pakem"],"r2":["SMAN 1 Ngaglik","SMAN 2 Ngaglik","SMAN 1 Turi"]},
{"d":"Caturtunggal","k":"Depok","kb":"Sleman","r1":["SMAN 1 Depok","SMAN 6 Yogyakarta","SMAN 9 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 11 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Condongcatur","k":"Depok","kb":"Sleman","r1":["SMAN 1 Depok","SMAN 6 Yogyakarta","SMAN 9 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 11 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Maguwoharjo","k":"Depok","kb":"Sleman","r1":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 8 Yogyakarta"],"r2":["SMAN 1 Kalasan","SMAN 2 Ngaglik","SMAN 1 Prambanan"]},
{"d":"Ambarketawang","k":"Gamping","kb":"Sleman","r1":["SMAN 1 Gamping","SMAN 1 Godean","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 10 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Balecatur","k":"Gamping","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Gamping","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 10 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Banyuraden","k":"Gamping","kb":"Sleman","r1":["SMAN 1 Gamping","SMAN 2 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 10 Yogyakarta","SMAN 7 Yogyakarta"]},
{"d":"Nogotirto","k":"Gamping","kb":"Sleman","r1":["SMAN 1 Gamping","SMAN 1 Godean","SMAN 2 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 10 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Trihanggo","k":"Gamping","kb":"Sleman","r1":["SMAN 11 Yogyakarta","SMAN 2 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 1 Gamping","SMAN 1 Mlati","SMAN 1 Yogyakarta"]},
{"d":"Sidoagung","k":"Godean","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Gamping","SMAN 1 Godean"],"r2":["SMAN 1 Minggir","SMAN 1 Mlati","SMAN 2 Yogyakarta"]},
{"d":"Sidoarum","k":"Godean","kb":"Sleman","r1":["SMAN 1 Gamping","SMAN 1 Godean","SMAN 2 Yogyakarta"],"r2":["SMAN 1 Mlati","SMAN 4 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Sidokarto","k":"Godean","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Gamping","SMAN 1 Godean"],"r2":["SMAN 1 Mlati","SMAN 2 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Sidoluhur","k":"Godean","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Gamping","SMAN 1 Godean"],"r2":["SMAN 1 Minggir","SMAN 1 Mlati","SMAN 1 Seyegan"]},
{"d":"Sidomoyo","k":"Godean","kb":"Sleman","r1":["SMAN 1 Gamping","SMAN 1 Godean","SMAN 1 Mlati"],"r2":["SMAN 2 Yogyakarta","SMAN 4 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Sidomulyo","k":"Godean","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Gamping","SMAN 1 Godean"],"r2":["SMAN 1 Minggir","SMAN 1 Mlati","SMAN 2 Yogyakarta"]},
{"d":"Sidorejo","k":"Godean","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Godean","SMAN 1 Minggir"],"r2":["SMAN 1 Gamping","SMAN 1 Mlati","SMAN 1 Seyegan"]},
{"d":"Purwomartani","k":"Kalasan","kb":"Sleman","r1":["SMAN 1 Depok","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Selomartani","k":"Kalasan","kb":"Sleman","r1":["SMAN 1 Kalasan","SMAN 2 Ngaglik","SMAN 1 Ngemplak"],"r2":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 1 Prambanan"]},
{"d":"Tamanmartani","k":"Kalasan","kb":"Sleman","r1":["SMAN 1 Kalasan","SMAN 1 Ngemplak","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 2 Ngaglik"]},
{"d":"Tirtomartani","k":"Kalasan","kb":"Sleman","r1":["SMAN 1 Kalasan","SMAN 1 Ngemplak","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 2 Ngaglik"]},
{"d":"Sendangagung","k":"Minggir","kb":"Sleman","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Sedayu","SMAN 1 Godean","SMAN 1 Seyegan"]},
{"d":"Sendangarum","k":"Minggir","kb":"Sleman","r1":["SMAN 1 Kalibawang","SMAN 1 Godean","SMAN 1 Minggir"],"r2":["SMAN 1 Sedayu","SMAN 1 Girimulyo","SMAN 1 Seyegan"]},
{"d":"Sendangmulyo","k":"Minggir","kb":"Sleman","r1":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Minggir"],"r2":["SMAN 1 Sedayu","SMAN 1 Godean","SMAN 1 Seyegan"]},
{"d":"Sendangrejo","k":"Minggir","kb":"Sleman","r1":["SMAN 1 Kalibawang","SMAN 1 Minggir","SMAN 1 Seyegan"],"r2":["SMAN 1 Sedayu","SMAN 1 Godean","SMAN 1 Tempel"]},
{"d":"Sendangsari","k":"Minggir","kb":"Sleman","r1":["SMAN 1 Kalibawang","SMAN 1 Minggir","SMAN 1 Seyegan"],"r2":["SMAN 1 Girimulyo","SMAN 1 Godean","SMAN 1 Tempel"]},
{"d":"Sendangadi","k":"Mlati","kb":"Sleman","r1":["SMAN 1 Mlati","SMAN 11 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 1 Gamping","SMAN 1 Ngaglik","SMAN 2 Yogyakarta"]},
{"d":"Sinduadi","k":"Mlati","kb":"Sleman","r1":["SMAN 11 Yogyakarta","SMAN 2 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 1 Mlati","SMAN 3 Yogyakarta","SMAN 9 Yogyakarta"]},
{"d":"Sumberadi","k":"Mlati","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 1 Sleman","SMAN 2 Sleman"],"r2":["SMAN 1 Mlati","SMAN 1 Tempel","SMAN 2 Yogyakarta"]},
{"d":"Tirtoadi","k":"Mlati","kb":"Sleman","r1":["SMAN 1 Gamping","SMAN 2 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 1 Godean","SMAN 1 Mlati","SMAN 1 Seyegan"]},
{"d":"Tlogoadi","k":"Mlati","kb":"Sleman","r1":["SMAN 2 Sleman","SMAN 2 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 1 Godean","SMAN 1 Mlati","SMAN 1 Seyegan"]},
{"d":"Sumberagung","k":"Moyudan","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Godean","SMAN 1 Minggir"],"r2":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Seyegan"]},
{"d":"Sumberarum","k":"Moyudan","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Girimulyo","SMAN 1 Minggir"],"r2":["SMAN 1 Kalibawang","SMAN 1 Sentolo","SMAN 1 Godean"]},
{"d":"Sumberrahayu","k":"Moyudan","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Sentolo","SMAN 1 Minggir"],"r2":["SMAN 1 Girimulyo","SMAN 1 Kalibawang","SMAN 1 Wates"]},
{"d":"Sumbersari","k":"Moyudan","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Godean","SMAN 1 Minggir"],"r2":["SMAN 1 Girimulyo","SMAN 1 Sentolo","SMAN 1 Gamping"]},
{"d":"Donoharjo","k":"Ngaglik","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Sleman","SMAN 1 Turi"],"r2":["SMAN 2 Ngaglik","SMAN 1 Pakem","SMAN 1 Sleman"]},
{"d":"Minomartani","k":"Ngaglik","kb":"Sleman","r1":["SMAN 1 Depok","SMAN 2 Ngaglik","SMAN 2 Sleman"],"r2":["SMAN 1 Ngaglik","SMAN 1 Ngemplak","SMAN 4 Yogyakarta"]},
{"d":"Sardonoharjo","k":"Ngaglik","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Ngaglik","SMAN 2 Sleman"],"r2":["SMAN 1 Mlati","SMAN 1 Ngemplak","SMAN 1 Pakem"]},
{"d":"Sariharjo","k":"Ngaglik","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Sleman","SMAN 11 Yogyakarta"],"r2":["SMAN 1 Mlati","SMAN 2 Ngaglik","SMAN 1 Sleman"]},
{"d":"Sinduharjo","k":"Ngaglik","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Ngaglik","SMAN 2 Sleman"],"r2":["SMAN 1 Ngemplak","SMAN 1 Pakem","SMAN 1 Sleman"]},
{"d":"Sukoharjo","k":"Ngaglik","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Ngaglik","SMAN 1 Ngemplak"],"r2":["SMAN 1 Cangkringan","SMAN 1 Pakem","SMAN 2 Sleman"]},
{"d":"Bimomartani","k":"Ngemplak","kb":"Sleman","r1":["SMAN 1 Kalasan","SMAN 2 Ngaglik","SMAN 1 Ngemplak"],"r2":["SMAN 1 Cangkringan","SMAN 1 Ngaglik","SMAN 1 Pakem"]},
{"d":"Sindumartani","k":"Ngemplak","kb":"Sleman","r1":["SMAN 1 Kalasan","SMAN 2 Ngaglik","SMAN 1 Ngemplak"],"r2":["SMAN 1 Cangkringan","SMAN 1 Ngaglik","SMAN 1 Pakem"]},
{"d":"Umbulmartani","k":"Ngemplak","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 2 Ngaglik","SMAN 1 Ngemplak"],"r2":["SMAN 1 Ngaglik","SMAN 1 Pakem","SMAN 1 Turi"]},
{"d":"Wedomartani","k":"Ngemplak","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Ngaglik","SMAN 1 Ngemplak"],"r2":["SMAN 1 Cangkringan","SMAN 1 Pakem","SMAN 2 Sleman"]},
{"d":"Widodomartani","k":"Ngemplak","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Ngaglik","SMAN 1 Ngemplak"],"r2":["SMAN 1 Cangkringan","SMAN 1 Pakem","SMAN 2 Sleman"]},
{"d":"Candibinangun","k":"Pakem","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 1 Pakem","SMAN 2 Sleman"],"r2":["SMAN 1 Cangkringan","SMAN 2 Ngaglik","SMAN 1 Sleman"]},
{"d":"Hargobinangun","k":"Pakem","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 1 Ngaglik","SMAN 1 Pakem"],"r2":["SMAN 2 Ngaglik","SMAN 1 Ngemplak","SMAN 2 Sleman"]},
{"d":"Hargobinangun","k":"Pakem","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 1 Ngaglik","SMAN 1 Pakem"],"r2":["SMAN 2 Ngaglik","SMAN 1 Ngemplak","SMAN 2 Sleman"]},
{"d":"Pakembinangun","k":"Pakem","kb":"Sleman","r1":["SMAN 1 Cangkringan","SMAN 1 Ngaglik","SMAN 1 Pakem"],"r2":["SMAN 2 Ngaglik","SMAN 1 Ngemplak","SMAN 2 Sleman"]},
{"d":"Purwobinangun","k":"Pakem","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 1 Pakem","SMAN 2 Sleman"],"r2":["SMAN 1 Cangkringan","SMAN 2 Ngaglik","SMAN 1 Sleman"]},
{"d":"Bokoharjo","k":"Prambanan","kb":"Sleman","r1":["SMAN 1 Kalasan","SMAN 1 Ngemplak","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 2 Ngaglik"]},
{"d":"Gayamharjo","k":"Prambanan","kb":"Sleman","r1":["SMAN 1 Patuk","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 1 Piyungan","SMAN 1 Ngemplak"]},
{"d":"Madurejo","k":"Prambanan","kb":"Sleman","r1":["SMAN 1 Piyungan","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 8 Yogyakarta"]},
{"d":"Sambirejo","k":"Prambanan","kb":"Sleman","r1":["SMAN 1 Banguntapan","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Piyungan","SMAN 1 Depok","SMAN 1 Ngemplak"]},
{"d":"Sumberharjo","k":"Prambanan","kb":"Sleman","r1":["SMAN 1 Piyungan","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 1 Depok","SMAN 8 Yogyakarta"]},
{"d":"Wukirharjo","k":"Prambanan","kb":"Sleman","r1":["SMAN 1 Patuk","SMAN 1 Kalasan","SMAN 1 Prambanan"],"r2":["SMAN 1 Banguntapan","SMAN 2 Banguntapan","SMAN 1 Piyungan"]},
{"d":"Margoagung","k":"Seyegan","kb":"Sleman","r1":["SMAN 1 Mlati","SMAN 1 Seyegan","SMAN 1 Sleman"],"r2":["SMAN 1 Godean","SMAN 1 Minggir","SMAN 1 Tempel"]},
{"d":"Margodadi","k":"Seyegan","kb":"Sleman","r1":["SMAN 1 Godean","SMAN 1 Mlati","SMAN 1 Seyegan"],"r2":["SMAN 1 Gamping","SMAN 1 Sleman","SMAN 1 Tempel"]},
{"d":"Margokaton","k":"Seyegan","kb":"Sleman","r1":["SMAN 1 Mlati","SMAN 1 Seyegan","SMAN 1 Tempel"],"r2":["SMAN 1 Godean","SMAN 1 Minggir","SMAN 1 Sleman"]},
{"d":"Margoluwih","k":"Seyegan","kb":"Sleman","r1":["SMAN 1 Sedayu","SMAN 1 Godean","SMAN 1 Seyegan"],"r2":["SMAN 1 Gamping","SMAN 1 Minggir","SMAN 1 Yogyakarta"]},
{"d":"Margomulyo","k":"Seyegan","kb":"Sleman","r1":["SMAN 1 Mlati","SMAN 1 Seyegan","SMAN 1 Sleman"],"r2":["SMAN 1 Godean","SMAN 1 Minggir","SMAN 1 Tempel"]},
{"d":"Caturharjo","k":"Sleman","kb":"Sleman","r1":["SMAN 1 Seyegan","SMAN 1 Sleman","SMAN 1 Tempel"],"r2":["SMAN 1 Mlati","SMAN 2 Sleman","SMAN 1 Turi"]},
{"d":"Pandowoharjo","k":"Sleman","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 1 Sleman","SMAN 2 Sleman"],"r2":["SMAN 1 Mlati","SMAN 1 Tempel","SMAN 1 Turi"]},
{"d":"Tridadi","k":"Sleman","kb":"Sleman","r1":["SMAN 1 Mlati","SMAN 1 Sleman","SMAN 2 Sleman"],"r2":["SMAN 1 Ngaglik","SMAN 1 Seyegan","SMAN 1 Turi"]},
{"d":"Triharjo","k":"Sleman","kb":"Sleman","r1":["SMAN 1 Seyegan","SMAN 1 Sleman","SMAN 2 Sleman"],"r2":["SMAN 1 Mlati","SMAN 1 Ngaglik","SMAN 1 Tempel"]},
{"d":"Trimulyo","k":"Sleman","kb":"Sleman","r1":["SMAN 1 Sleman","SMAN 2 Sleman","SMAN 1 Turi"],"r2":["SMAN 1 Ngaglik","SMAN 1 Seyegan","SMAN 1 Tempel"]},
{"d":"Banyurejo","k":"Tempel","kb":"Sleman","r1":["SMAN 1 Mlati","SMAN 1 Seyegan","SMAN 1 Tempel"],"r2":["SMAN 1 Godean","SMAN 1 Sleman","SMAN 2 Sleman"]},
{"d":"Lumbungrejo","k":"Tempel","kb":"Sleman","r1":["SMAN 1 Sleman","SMAN 1 Tempel","SMAN 1 Turi"],"r2":["SMAN 1 Ngaglik","SMAN 1 Seyegan","SMAN 2 Sleman"]},
{"d":"Margorejo","k":"Tempel","kb":"Sleman","r1":["SMAN 1 Tempel","SMAN 1 Sleman","SMAN 1 Turi"],"r2":["SMAN 1 Ngaglik","SMAN 2 Sleman","SMAN 1 Seyegan"]},
{"d":"Merdikorejo","k":"Tempel","kb":"Sleman","r1":["SMAN 1 Sleman","SMAN 1 Tempel","SMAN 1 Turi"],"r2":["SMAN 1 Ngaglik","SMAN 1 Pakem","SMAN 2 Sleman"]},
{"d":"Mororejo","k":"Tempel","kb":"Sleman","r1":["SMAN 1 Seyegan","SMAN 1 Sleman","SMAN 1 Tempel"],"r2":["SMAN 1 Mlati","SMAN 1 Ngaglik","SMAN 2 Sleman"]},
{"d":"Pondokrejo","k":"Tempel","kb":"Sleman","r1":["SMAN 1 Seyegan","SMAN 1 Sleman","SMAN 1 Tempel"],"r2":["SMAN 1 Mlati","SMAN 2 Sleman","SMAN 1 Turi"]},
{"d":"Sumberrejo","k":"Tempel","kb":"Sleman","r1":["SMAN 1 Seyegan","SMAN 1 Sleman","SMAN 1 Tempel"],"r2":["SMAN 1 Mlati","SMAN 2 Sleman","SMAN 1 Turi"]},
{"d":"Tambakrejo","k":"Tempel","kb":"Sleman","r1":["SMAN 1 Seyegan","SMAN 1 Sleman","SMAN 1 Tempel"],"r2":["SMAN 1 Mlati","SMAN 2 Sleman","SMAN 1 Turi"]},
{"d":"Bangunkerto","k":"Turi","kb":"Sleman","r1":["SMAN 1 Sleman","SMAN 2 Sleman","SMAN 1 Turi"],"r2":["SMAN 1 Ngaglik","SMAN 1 Seyegan","SMAN 1 Tempel"]},
{"d":"Donokerto","k":"Turi","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Sleman","SMAN 1 Turi"],"r2":["SMAN 1 Cangkringan","SMAN 2 Ngaglik","SMAN 1 Sleman"]},
{"d":"Girikerto","k":"Turi","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 2 Sleman","SMAN 1 Turi"],"r2":["SMAN 1 Cangkringan","SMAN 2 Ngaglik","SMAN 1 Sleman"]},
{"d":"Wonokerto","k":"Turi","kb":"Sleman","r1":["SMAN 1 Ngaglik","SMAN 1 Sleman","SMAN 1 Turi"],"r2":["SMAN 1 Cangkringan","SMAN 2 Sleman","SMAN 1 Tempel"]},
{"d":"Bausasran","k":"Danurejan","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 9 Yogyakarta"],"r2":["SMAN 11 Yogyakarta","SMAN 8 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Suryatmajan","k":"Danurejan","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 10 Yogyakarta"],"r2":["SMAN 9 Yogyakarta","SMAN 11 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Tegalpanggung","k":"Danurejan","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 9 Yogyakarta"],"r2":["SMAN 10 Yogyakarta","SMAN 11 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Pringgokusuman","k":"Gedongtengen","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 2 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 7 Yogyakarta","SMAN 4 Yogyakarta"]},
{"d":"Sosromenduran","k":"Gedongtengen","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 10 Yogyakarta"],"r2":["SMAN 11 Yogyakarta","SMAN 4 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Baciro","k":"Gondokusuman","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 9 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 6 Yogyakarta","SMAN 11 Yogyakarta","SMAN 4 Yogyakarta"]},
{"d":"Demangan","k":"Gondokusuman","kb":"Yogyakarta","r1":["SMAN 6 Yogyakarta","SMAN 9 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 11 Yogyakarta","SMAN 4 Yogyakarta"]},
{"d":"Klitren","k":"Gondokusuman","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 9 Yogyakarta"],"r2":["SMAN 11 Yogyakarta","SMAN 4 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Kotabaru","k":"Gondokusuman","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 9 Yogyakarta"],"r2":["SMAN 10 Yogyakarta","SMAN 11 Yogyakarta","SMAN 8 Yogyakarta"]},
{"d":"Terban","k":"Gondokusuman","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 9 Yogyakarta"],"r2":["SMAN 11 Yogyakarta","SMAN 2 Yogyakarta","SMAN 4 Yogyakarta"]},
{"d":"Ngupasan","k":"Gondomanan","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 10 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 6 Yogyakarta","SMAN 9 Yogyakarta","SMAN 7 Yogyakarta"]},
{"d":"Prawirodirjan","k":"Gondomanan","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 10 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 6 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Bumijo","k":"Jetis","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 2 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 6 Yogyakarta","SMAN 11 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Cokrodiningratan","k":"Jetis","kb":"Yogyakarta","r1":["SMAN 6 Yogyakarta","SMAN 11 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 9 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Gowongan","k":"Jetis","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 11 Yogyakarta"],"r2":["SMAN 10 Yogyakarta","SMAN 2 Yogyakarta","SMAN 4 Yogyakarta"]},
{"d":"Prenggan","k":"Kotagede","kb":"Yogyakarta","r1":["SMAN 2 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 1 Banguntapan","SMAN 1 Sewon","SMAN 7 Yogyakarta"]},
{"d":"Purbayan","k":"Kotagede","kb":"Yogyakarta","r1":["SMAN 1 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 2 Banguntapan","SMAN 1 Piyungan","SMAN 7 Yogyakarta"]},
{"d":"Rejowinangun","k":"Kotagede","kb":"Yogyakarta","r1":["SMAN 1 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 2 Banguntapan","SMAN 3 Yogyakarta","SMAN 7 Yogyakarta"]},
{"d":"Kadipaten","k":"Kraton","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 3 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Panembahan","k":"Kraton","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 3 Yogyakarta","SMAN 6 Yogyakarta"]},
{"d":"Patehan","k":"Kraton","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 4 Yogyakarta"]},
{"d":"Gedongkiwo","k":"Mantrijeron","kb":"Yogyakarta","r1":["SMAN 1 Kasihan","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Sewon","SMAN 1 Gamping","SMAN 10 Yogyakarta"]},
{"d":"Mantrijeron","k":"Mantrijeron","kb":"Yogyakarta","r1":["SMAN 1 Kasihan","SMAN 1 Sewon","SMAN 7 Yogyakarta"],"r2":["SMAN 10 Yogyakarta","SMAN 5 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Suryodiningratan","k":"Mantrijeron","kb":"Yogyakarta","r1":["SMAN 1 Kasihan","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Sewon","SMAN 10 Yogyakarta","SMAN 5 Yogyakarta"]},
{"d":"Brontokusuman","k":"Mergangsan","kb":"Yogyakarta","r1":["SMAN 1 Kasihan","SMAN 10 Yogyakarta","SMAN 7 Yogyakarta"],"r2":["SMAN 5 Yogyakarta","SMAN 8 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Keparakan","k":"Mergangsan","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 5 Yogyakarta","SMAN 7 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 3 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Wirogunan","k":"Mergangsan","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 7 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 9 Yogyakarta","SMAN 5 Yogyakarta"]},
{"d":"Ngampilan","k":"Ngampilan","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 3 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Notoprajan","k":"Ngampilan","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 3 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Gunungketur","k":"Pakualaman","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 10 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 6 Yogyakarta","SMAN 9 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Purwokinanti","k":"Pakualaman","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 10 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 6 Yogyakarta","SMAN 9 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Bener","k":"Tegalrejo","kb":"Yogyakarta","r1":["SMAN 2 Yogyakarta","SMAN 4 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Gamping","SMAN 6 Yogyakarta","SMAN 11 Yogyakarta"]},
{"d":"Karangwaru","k":"Tegalrejo","kb":"Yogyakarta","r1":["SMAN 6 Yogyakarta","SMAN 11 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 9 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Kricak","k":"Tegalrejo","kb":"Yogyakarta","r1":["SMAN 11 Yogyakarta","SMAN 2 Yogyakarta","SMAN 4 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 6 Yogyakarta","SMAN 9 Yogyakarta"]},
{"d":"Tegalrejo","k":"Tegalrejo","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 2 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 3 Yogyakarta","SMAN 4 Yogyakarta"]},
{"d":"Giwangan","k":"Umbulharjo","kb":"Yogyakarta","r1":["SMAN 2 Banguntapan","SMAN 5 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 1 Pleret","SMAN 1 Sewon","SMAN 7 Yogyakarta"]},
{"d":"Mujamuju","k":"Umbulharjo","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 9 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 1 Banguntapan","SMAN 6 Yogyakarta","SMAN 5 Yogyakarta"]},
{"d":"Pandeyan","k":"Umbulharjo","kb":"Yogyakarta","r1":["SMAN 5 Yogyakarta","SMAN 7 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 9 Yogyakarta","SMAN 10 Yogyakarta"]},
{"d":"Semaki","k":"Umbulharjo","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 9 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 6 Yogyakarta","SMAN 10 Yogyakarta","SMAN 1 Yogyakarta"]},
{"d":"Sorosutan","k":"Umbulharjo","kb":"Yogyakarta","r1":["SMAN 1 Sewon","SMAN 5 Yogyakarta","SMAN 7 Yogyakarta"],"r2":["SMAN 2 Banguntapan","SMAN 1 Kasihan","SMAN 8 Yogyakarta"]},
{"d":"Tahunan","k":"Umbulharjo","kb":"Yogyakarta","r1":["SMAN 3 Yogyakarta","SMAN 10 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 9 Yogyakarta","SMAN 5 Yogyakarta","SMAN 7 Yogyakarta"]},
{"d":"Warungboto","k":"Umbulharjo","kb":"Yogyakarta","r1":["SMAN 5 Yogyakarta","SMAN 7 Yogyakarta","SMAN 8 Yogyakarta"],"r2":["SMAN 1 Banguntapan","SMAN 3 Yogyakarta","SMAN 10 Yogyakarta"]},
{"d":"Pakuncen","k":"Wirobrajan","kb":"Yogyakarta","r1":["SMAN 10 Yogyakarta","SMAN 2 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Kasihan","SMAN 3 Yogyakarta","SMAN 7 Yogyakarta"]},
{"d":"Patangpuluhan","k":"Wirobrajan","kb":"Yogyakarta","r1":["SMAN 1 Kasihan","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 1 Gamping","SMAN 10 Yogyakarta","SMAN 2 Yogyakarta"]},
{"d":"Wirobrajan","k":"Wirobrajan","kb":"Yogyakarta","r1":["SMAN 1 Kasihan","SMAN 7 Yogyakarta","SMAN 1 Yogyakarta"],"r2":["SMAN 3 Yogyakarta","SMAN 10 Yogyakarta","SMAN 2 Yogyakarta"]}
];


// Desa Perbatasan Jateng yang masuk Rayon 1 SMKN (dari Tabel Juknis)
const SMKN_BORDER_VILLAGES = [
{"d":"Banyuripan","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Beluk","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Bogem","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Dukuh","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Gunung Gajah","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Jambakan","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Jarum","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Nengahan","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Ngerangan","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Paseban","k":"Bayat","kb":"Klaten","s":["SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Barepan","k":"Cawas","kb":"Klaten","s":["SMKN 1 Ngawen"]},
{"d":"Bawak","k":"Cawas","kb":"Klaten","s":["SMKN 1 Ngawen"]},
{"d":"Bendungan","k":"Cawas","kb":"Klaten","s":["SMKN 1 Ngawen"]},
{"d":"Burikan","k":"Cawas","kb":"Klaten","s":["SMKN 1 Ngawen"]},
{"d":"Karangasem","k":"Cawas","kb":"Klaten","s":["SMKN 1 Ngawen"]},
{"d":"Kedungampel","k":"Cawas","kb":"Klaten","s":["SMKN 1 Ngawen"]},
{"d":"Nanggulan","k":"Cawas","kb":"Klaten","s":["SMKN 1 Ngawen"]},
{"d":"Tugu","k":"Cawas","kb":"Klaten","s":["SMKN 1 Ngawen"]},
{"d":"Gentan","k":"Gantiwarno","kb":"Klaten","s":["SMKN 1 Gedangsari","SMKN 2 Gedangsari"]},
{"d":"Gesikan","k":"Gantiwarno","kb":"Klaten","s":["SMKN 2 Gedangsari"]},
{"d":"Jogoprayan","k":"Gantiwarno","kb":"Klaten","s":["SMKN 1 Gedangsari","SMKN 2 Gedangsari"]},
{"d":"Karangturi","k":"Gantiwarno","kb":"Klaten","s":["SMKN 1 Gedangsari","SMKN 2 Gedangsari"]},
{"d":"Kragilan","k":"Gantiwarno","kb":"Klaten","s":["SMKN 1 Gedangsari","SMKN 2 Gedangsari"]},
{"d":"Mlese","k":"Gantiwarno","kb":"Klaten","s":["SMKN 2 Gedangsari"]},
{"d":"Balerante","k":"Kemalang","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Bawukan","k":"Kemalang","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Panggung","k":"Kemalang","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Kebonalas","k":"Manisrenggo","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Kecemen","k":"Manisrenggo","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Kepurun","k":"Manisrenggo","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Kranggan","k":"Manisrenggo","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Leses","k":"Manisrenggo","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Ngemplak Seneng","k":"Manisrenggo","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Sapen","k":"Manisrenggo","kb":"Klaten","s":["SMKN 1 Cangkringan"]},
{"d":"Taskombang","k":"Manisrenggo","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Brajan","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Bugisan","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Cucukan","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Geneng","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Kebondalem Lor","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Kebondalemkidul","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Kemudo","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Kokosan","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Kotesan","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Pereng","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Randusari","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Sanggrahan","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Sengon","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Taji","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Tlogo","k":"Prambanan","kb":"Klaten","s":["SMKN 1 Kalasan"]},
{"d":"Kadilanggon","k":"Wedi","kb":"Klaten","s":["SMKN 1 Gedangsari","SMKN 2 Gedangsari"]},
{"d":"Kaligayam","k":"Wedi","kb":"Klaten","s":["SMKN 1 Gedangsari","SMKN 1 Ngawen","SMKN 2 Gedangsari"]},
{"d":"Melikan","k":"Wedi","kb":"Klaten","s":["SMKN 2 Gedangsari"]},
{"d":"Pacing","k":"Wedi","kb":"Klaten","s":["SMKN 1 Gedangsari","SMKN 2 Gedangsari"]},
{"d":"Bligo","k":"Ngluwar","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Pakunden","k":"Ngluwar","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Mantingan","k":"Salam","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Salam","k":"Salam","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Sucen","k":"Salam","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Kaliurang","k":"Srumbung","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Kamongan","k":"Srumbung","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Kemiren","k":"Srumbung","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Sudimoro","k":"Srumbung","kb":"Magelang","s":["SMKN 1 Tempel"]},
{"d":"Bapangsari","k":"Bagelen","kb":"Purworejo","s":["SMKN 1 Temon"]},
{"d":"Dadirejo","k":"Bagelen","kb":"Purworejo","s":["SMKN 1 Kokap","SMKN 1 Temon"]},
{"d":"Durensari","k":"Bagelen","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Kokap"]},
{"d":"Semono","k":"Bagelen","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Kokap"]},
{"d":"Pandanrejo","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Girimulyo"]},
{"d":"Donorejo","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Kokap"]},
{"d":"Gunungwangi","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Hardimulyo","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Jatirejo","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Kokap"]},
{"d":"Ngaran","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Pandanrejo","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Pucungroto","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Samigaluh"]},
{"d":"Purbowono","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Samigaluh"]},
{"d":"Somowono","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Samigaluh"]},
{"d":"Tawangsari","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Samigaluh"]},
{"d":"Tlogobulu","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Samigaluh"]},
{"d":"Tlogoguwo","k":"Kaligesing","kb":"Purworejo","s":["SMKN 1 Girimulyo","SMKN 1 Samigaluh"]},
{"d":"Banyuasin Kembaran","k":"Loano","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Banyuasin Separe","k":"Loano","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Kaliglagah","k":"Loano","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Ngargosari","k":"Loano","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Tridadi","k":"Loano","kb":"Purworejo","s":["SMKN 1 Samigaluh"]},
{"d":"Banjarsari","k":"Purwodadi","kb":"Purworejo","s":["SMKN 1 Temon"]},
{"d":"Gedangan","k":"Purwodadi","kb":"Purworejo","s":["SMKN 1 Temon"]},
{"d":"Jogoboyo","k":"Purwodadi","kb":"Purworejo","s":["SMKN 1 Temon"]},
{"d":"Jogoresan","k":"Purwodadi","kb":"Purworejo","s":["SMKN 1 Temon"]},
{"d":"Karanganyar","k":"Purwodadi","kb":"Purworejo","s":["SMKN 1 Temon"]},
{"d":"Karangsari","k":"Purwodadi","kb":"Purworejo","s":["SMKN 1 Temon"]},
{"d":"Watukuro","k":"Purwodadi","kb":"Purworejo","s":["SMKN 1 Temon"]},
{"d":"Grogol","k":"Weru","kb":"Sukoharjo","s":["SMKN 1 Ngawen"]},
{"d":"Jatingarang","k":"Weru","kb":"Sukoharjo","s":["SMKN 1 Ngawen"]},
{"d":"Karakan","k":"Weru","kb":"Sukoharjo","s":["SMKN 1 Ngawen"]},
{"d":"Karanganyar","k":"Weru","kb":"Sukoharjo","s":["SMKN 1 Ngawen"]},
{"d":"Karangtengah","k":"Weru","kb":"Sukoharjo","s":["SMKN 1 Ngawen"]},
{"d":"Karangwuni","k":"Weru","kb":"Sukoharjo","s":["SMKN 1 Ngawen"]},
{"d":"Krajan","k":"Weru","kb":"Sukoharjo","s":["SMKN 1 Ngawen"]},
{"d":"Basuhan","k":"Eromoko","kb":"Wonogiri","s":["SMKN 1 Ponjong"]},
{"d":"Pasekan","k":"Eromoko","kb":"Wonogiri","s":["SMKN 1 Ponjong"]},
{"d":"Pucung","k":"Eromoko","kb":"Wonogiri","s":["SMKN 1 Ponjong"]},
{"d":"Gebangharjo","k":"Pracimantoro","kb":"Wonogiri","s":["SMKN 1 Ponjong"]},
{"d":"Glinggang","k":"Pracimantoro","kb":"Wonogiri","s":["SMKN 1 Ponjong"]},
{"d":"Pracimantoro","k":"Pracimantoro","kb":"Wonogiri","s":["SMKN 1 Ponjong"]},
{"d":"Tubokarto","k":"Pracimantoro","kb":"Wonogiri","s":["SMKN 1 Ponjong"]},
{"d":"Wonodadi","k":"Pracimantoro","kb":"Wonogiri","s":["SMKN 1 Ponjong"]}
];

// Export untuk browser / ES module
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { SMAN_RAYON, SMKN_BORDER_VILLAGES };
} else {
  window.RAYON_DATA = { SMAN_RAYON, SMKN_BORDER_VILLAGES };
}